language: python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - black --check .
  - pytest -vv -s
before_install:
  - sudo apt-get install whois
